#pragma once
#include <cstdint>
extern const uint8_t ZAP_ICON[8];
extern const uint8_t CV_ICON[8];
extern const uint8_t DOWN_BTN_ICON[8];
extern const uint8_t UP_ICON[8];
extern const uint8_t DOWN_ICON[8];
extern const uint8_t UP_DOWN_ICON[8];
extern const uint8_t CLOCK_ICON[8];
extern const uint8_t GAUGE_ICON[8];
extern const uint8_t RANDOM_ICON[8];
extern const uint8_t ROTATE_R_ICON[8];
extern const uint8_t ROTATE_L_ICON[8];
extern const uint8_t CLOSED_ICON[8];
extern const uint8_t OPEN_ICON[8];
extern const uint8_t GATE_ICON[8];
extern const uint8_t MOD_ICON[8];
extern const uint8_t CHECK_ON_ICON[8];
extern const uint8_t CHECK_OFF_ICON[8];
extern const uint8_t STAIRS_ICON[8];
extern const uint8_t UP_BTN_ICON[8];
extern const uint8_t RESET_ICON[8];
extern const uint8_t LOOP_ICON[8];
extern const uint8_t X_NOTE_ICON[8];
// Mirrors vendor HSicons.h.
extern const uint8_t LEFT_ICON[8];
extern const uint8_t WAVEFORM_ICON[8];
extern const uint8_t NOTE_ICON[8];
extern const uint8_t NOTE4_ICON[8];
extern const uint8_t SILENT_PIGEON_ICON[8];
extern const uint8_t SINGING_PIGEON_ICON[8];
extern const uint8_t SCALE_ICON[8];
extern const uint8_t PLAY_ICON[8];
extern const uint8_t FAVORITE_ICON[8];
extern const uint8_t EDIT_ICON[8];
extern const uint8_t LINK_ICON[8];
extern const uint8_t BEND_ICON[8];
extern const uint8_t METRO_L_ICON[8];
extern const uint8_t METRO_R_ICON[8];
extern const uint8_t NOTE2_ICON[8];
extern const uint8_t UP_ARROWS_BTT[18];
extern const uint8_t DOWN_ARROWS_BTT[18];
extern const uint8_t SMALL_ONE[3];
extern const uint8_t TEENS_8X8[20 * 8];
extern const uint8_t NOTE_NAMES[12 * 8];
