#pragma once
#include <cstdint>
namespace PhzIcons {
extern const uint8_t logic[8];
extern const uint8_t dualAttenuverter[8];
extern const uint8_t brancher[8];
extern const uint8_t slew[8];
extern const uint8_t calculate[8];
extern const uint8_t burst[8];
extern const uint8_t gateDelay[8];
extern const uint8_t thresholdLogicNeuron[8];
extern const uint8_t button2[8];
extern const uint8_t compare[8];
extern const uint8_t cumulus[8];
extern const uint8_t gateVca[8];
extern const uint8_t clockDivider[8];
extern const uint8_t clockSkip[8];
extern const uint8_t envelopeFollower[8];
extern const uint8_t polyDiv[8];
extern const uint8_t rndWalk[8];
extern const uint8_t runglBook[8];
extern const uint8_t schmitt[8];
extern const uint8_t stairs[8];
extern const uint8_t switchApp[8];
extern const uint8_t voltage[8];
// Phase 4 additions
extern const uint8_t binaryCounter[8];
extern const uint8_t shiftGate[8];
extern const uint8_t trending[8];
extern const uint8_t probDiv[8];
extern const uint8_t AD_EG[8];
extern const uint8_t ADSR_EG[8];
extern const uint8_t gameOfLife[8];
// Phase 6 additions
extern const uint8_t vectorLFO[8];
extern const uint8_t vectorEG[8];
extern const uint8_t vectorMod[8];
extern const uint8_t vectorMorph[8];
extern const uint8_t lowerenz[8];
extern const uint8_t strum[8];
extern const uint8_t shredder[8];
extern const uint8_t carpeggio[8];
extern const uint8_t squanch[8];
extern const uint8_t chordinate[8];
extern const uint8_t dualQuantizer[8];
extern const uint8_t enigmaJr[8];
extern const uint8_t multiscale[8];
extern const uint8_t scaleDuet[8];
extern const uint8_t calibr8[8];
extern const uint8_t resetClk[8];
extern const uint8_t shuffle[8];
extern const uint8_t mixerBal[8];
extern const uint8_t scope[8];
}
