#include "HSUtils.h"
#include "OC_core.h"
#include "OC_strings.h"
#include "OC_DAC.h"
#include "HSClockManager.h"
#include <cstddef>

// Provide operator delete so vtables generated by `virtual ~HemisphereApplet()`
// resolve at link time. The shim never deletes via vtable (applets are
// constructed via placement-new in a fixed sram slot and destroyed via
// explicit ~HemisphereApplet() in hemispheres_swap), so this is unreachable
// in practice. NT firmware does not provide operator delete.
void operator delete(void*) noexcept {}
void operator delete(void*, std::size_t) noexcept {}
void operator delete[](void*) noexcept {}
void operator delete[](void*, std::size_t) noexcept {}

namespace OC {
namespace CORE {
volatile uint32_t ticks = 0;
}
}

// DAC channel objects. The shim switched OC_DAC.h from `enum DAC_CHANNEL` to
// the vendor `using DAC_CHANNEL = int` plus extern channel objects so the
// templated accessors (`template <DAC_CHANNEL &channel>`) bind to lvalues.
// Values mirror the prior enumerator ordinals (A=0, B=1, C=2, D=3) so every
// existing value-context use (Out, ClockOut casts) is unchanged.
DAC_CHANNEL DAC_CHANNEL_A = 0;
DAC_CHANNEL DAC_CHANNEL_B = 1;
DAC_CHANNEL DAC_CHANNEL_C = 2;
DAC_CHANNEL DAC_CHANNEL_D = 3;

namespace HS {
const char* help_strings[HS::HELP_LABEL_COUNT] = { nullptr };
int cursor_countdown[HS::APPLET_CURSOR_COUNT] = { 0 };
EncoderEditor enc_edit[HS::APPLET_CURSOR_COUNT] = {{ false }};
int gfx_offset = 0;
int gfx_offset_y = 0;
// Defaults are full screen (256 wide, 64 tall) so the harness, standalone
// runs, and probes see no clamp. Hosts overwrite per-frame before each
// per-applet render_view call.
int gfx_clip_w = 256;
int gfx_clip_h = 64;
// Popup-state globals. Mirrors vendor HSUtils.cpp:23-31. Host tests do
// not exercise popups; PokePopup is a no-op.
uint8_t qview = 0;
uint8_t mview = 0;
int q_edit = 0;
int midi_edit = 0;
PopupType popup_type = MENU_POPUP;
ErrMsgIndex msg_idx = NO_ERROR;
uint32_t popup_tick = 0;
void PokePopup(PopupType /*pop*/, ErrMsgIndex /*err*/) {}
void PokePopup(PopupType /*pop*/, const char* /*msg*/) {}
}

namespace OC {
namespace Strings {
const char* const capital_letters[] = { "A", "B", "C", "D", "E", "F", "G", "H" };
// Vendor OC_strings.cpp:67-69 verbatim. note_names is space-padded
// (two-char "C ", "C#", ...), note_names_unpadded omits trailing spaces.
const char* const note_names[12] = {
    "C ", "C#", "D ", "D#", "E ", "F ", "F#", "G ", "G#", "A ", "A#", "B "
};
const char* const note_names_unpadded[12] = {
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"
};
// Vendor OC_scales.cpp scale name lists. Scale-using applets (MultiScale,
// ScaleDuet) call OC::Strings::scale_names; the shim re-exports the
// scale names from braids_quantizer_scales for tight pitch labels.
const char* const scale_names[] = {
    "Off", "Semi", "Maj", "Min", "Dor", "Phr", "Lyd", "Mix", "Aeo", "Loc",
    "BluM", "BluR", "Pmaj", "Pmin", "Folk", "Japn", "Gam", "Gyps", "Arab",
    "Flam", "Whol", "Pyth", "Eb/4", "E/4", "Ea/4", "Bhai", "Gunk", "Mars",
    "User"
};
const char* const scale_names_short[] = {
    "Off", "Sm", "Maj", "Mn", "Do", "Ph", "Ly", "Mx", "Ae", "Lc",
    "BM", "BR", "Pj", "Pi", "Fk", "Jp", "Gm", "Gy", "Ar", "Fl",
    "Wh", "Py", "Eb", "E4", "Ea", "Bh", "Gn", "Mr", "Us"
};
// Harrington 1200 (APP_H1200) CV-source labels. Vendor OC_strings.cpp:88, four-
// channel (non-Teensy41) form. H1200's CV-source settings index this 0..4
// (H1200_CV_SOURCE_NONE..CV4); the trailing "A".."D" cover the slot CV sources
// the broader catalog uses. The shim owns these so Harrington 1200 needs no
// vendor OC_strings.cpp link (which would duplicate note_names/capital_letters,
// also defined above). globals.cpp is aggregated into every applet/app TU; the
// table is additive and referenced only by Harrington 1200.
const char* const cv_input_names_none[] = {
    " - ", "CV1", "CV2", "CV3", "CV4", "A", "B", "C", "D"
};
// Trigger-delay labels. Vendor OC_strings.cpp:123.
const char* const trigger_delay_times[kNumDelayTimes] = {
    "off", "120us", "240us", "360us", "480us", "1ms", "2ms", "4ms"
};
// BBGEN (APP_BBGEN) settings labels. Vendor OC_strings.cpp:73,115.
const char* const trigger_input_names[4] = { "TR1", "TR2", "TR3", "TR4" };
const char* const no_yes[] = { "No", "Yes" };
// BYTEBEATGEN (APP_BYTEBEATGEN) Equation setting labels. Vendor OC_strings.cpp:127.
const char* const bytebeat_equation_names[] = {
    "hope", "love", "life", "age", "clysm", "monk", "NERV", "Trurl",
    "Pirx", "Snaut", "Hari", "Kris", "Tichy", "Bregg", "Avon", "Orac"
};
// POLYLFO (APP_POLYLFO) Tap-tempo bool label. Vendor OC_strings.cpp:117.
const char* const off_on[] = { "off", "on" };
// ENVGEN (APP_ENVGEN) envelope-setting value labels. Vendor OC_strings.cpp:131,156,160.
const char* const envelope_shapes[11] = {
    "Lin", "Exp", "Quart", "Sine", "Ledge", "Cliff", "Gate", "BgDip", "MeDip", "LtDip", "Wiggl"
};
const char* const reset_behaviours[] = { "None", "SP", "SLP", "SL", "P" };
const char* const falling_gate_behaviours[] = { "Ignor", "Honor" };
// Vendor OC_strings.cpp:75 (non-Teensy41 layout: 13 entries).
const char* const trigger_input_names_none[] = {
    " - ", "TR1", "TR2", "TR3", "TR4", "CV1", "CV2", "CV3", "CV4", "A", "B", "C", "D"
};
// PASSENCORE (APP_PASSENCORE) scale-editor / chord-editor labels. The vendor
// OC_scale_edit.h and OC_chords_edit.h (both pulled by APP_PASSENCORE.h, even
// with the chord editor commented out) reference these at template-definition
// scope, so they must resolve. Bytes verbatim from vendor OC_strings.cpp.
const char* const scale_degrees_maj[] = { "I", "II", "III", "IV", "V", "VI", "VII" };
const char* const scale_degrees_min[] = { "i", "ii", "iii", "iv", "v", "vi", "vii" };
const char* const accidentals[] = { "bb", "b", "", "#", "##" };
const char* const scale_id[] = { ">#1", ">#2", ">#3", ">#4", " #1", " #2", " #3", " #4" };
const char* const channel_id[4] = { "#A", "#B", "#C", "#D" };
const char* const scaling_string[] = { "scaling " };
const char* const chord_property_names[] = { "Q", "V", "I", "B", "O" };
// DQ (APP_DQ / Meta-Q) setting value labels. Bytes verbatim from vendor
// OC_strings.cpp (cv_input_names:86, channel_trigger_sources:55,
// TM_aux_cv_destinations:152).
const char* const cv_input_names[] = { "CV1", "CV2", "CV3", "CV4" };
const char* const channel_trigger_sources[] = { "TR1", "TR2", "TR3", "TR4", "cnt+", "cnt-" };
const char* const TM_aux_cv_destinations[] = { "-", "rng", "len", "prb" };
// ASR (APP_ASR) setting value labels (vendor OC_strings.cpp:135,139,145, verbatim).
const char* const mult[] = {
    "0.05", "0.10", "0.15", "0.20", "0.25", "0.30", "0.35", "0.40", "0.45", "0.50",
    "0.55", "0.60", "0.65", "0.70", "0.75", "0.80", "0.85", "0.90", "0.95", "1.00",
    "1.05", "1.10", "1.15", "1.20", "1.25", "1.30", "1.35", "1.40", "1.45", "1.50",
    "1.55", "1.60", "1.65", "1.70", "1.75", "1.80", "1.85", "1.90", "1.95", "2.00"
};
const char* const integer_sequence_names[] = {
    "pi", "vnEck", "ssdn", "Dress", "PNinf", "Dsum", "Dsum4", "Dsum5", "CDn2", "Frcti"
};
const char* const integer_sequence_dirs[] = { "swing", "loop" };
// ASR integer-sequence digit tables (vendor OC_strings.cpp:168+, verbatim).
// Each holds the first kIntSeqLen terms the IntegerSequence source indexes.
const uint8_t pi_digits[kIntSeqLen] = {
    3,1,4,1,5,9,2,6,5,3,5,8,9,7,9,3,2,3,8,4,6,2,6,4,3,3,8,3,2,7,9,5,0,2,8,8,4,1,9,7,1,6,9,3,9,9,3,7,5,1,0,5,8,2,0,9,7,4,9,4,4,5,9,2,
    3,0,7,8,1,6,4,0,6,2,8,6,2,0,8,9,9,8,6,2,8,0,3,4,8,2,5,3,4,2,1,1,7,0,6,7,9,8,2,1,4,8,0,8,6,5,1,3,2,8,2,3,0,6,6,4,7,0,9,3,8,4,4,6
};
const uint8_t van_eck[kIntSeqLen] = {
    0,0,1,0,2,0,2,2,1,6,0,5,0,2,6,5,4,0,5,3,0,3,2,9,0,4,9,3,6,14,0,6,3,5,15,0,5,3,5,2,17,0,6,11,
    0,3,8,0,3,3,1,42,0,5,15,20,0,4,32,0,3,11,18,0,4,7,0,3,7,3,2,31,0,6,31,3,6,3,2,8,33,0,9,56,0,
    3,8,7,19,0,5,37,0,3,8,8,1,46,0,6,23,0,3,9,21,0,4,42,56,25,0,5,21,8,18,52,0,6,18,4,13,0,5,11,62,0,4,7
};
const uint8_t sum_of_squares_of_digits_of_n[kIntSeqLen] = {
    0,1,4,9,16,25,36,49,64,81,1,2,5,10,17,26,37,50,65,82,4,5,8,13,20,29,40,53,68,85,9,10,13,18,25,34,45,58,73,
    90,16,17,20,25,32,41,52,65,80,97,25,26,29,34,41,50,61,74,89,106,36,37,40,45,52,61,72,85,100,117,49,50,53,58,
    65,74,85,98,113,130,64,65,68,73,80,89,100,113,128,145,81,82,85,90,97,106,117,130,145,162,1,2,5,10,17,26,37,
    50,65,82,2,3,6,11,18,27,38,51,66,83,5,6,9,14,21,30,41,54
};
const uint8_t digsum_of_n[kIntSeqLen] = {
    0,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,10,2,3,4,5,6,7,8,9,10,11,3,4,5,6,7,8,9,10,11,12,4,5,6,7,8,9,10,11,12,13,5,6,7,8,9,
    10,11,12,13,14,6,7,8,9,10,11,12,13,14,15,7,8,9,10,11,12,13,14,15,16,8,9,10,11,12,13,14,15,16,17,9,10,11,12,13,14,15,16,17,
    18,1,2,3,4,5,6,7,8,9,10,2,3,4,5,6,7,8,9,10,11,3,4,5,6,7,8,9,10
};
const uint8_t digsum_of_n_base4[kIntSeqLen] = {
    0,1,2,3,1,2,3,4,2,3,4,5,3,4,5,6,1,2,3,4,2,3,4,5,3,4,5,6,4,5,6,7,2,3,4,5,3,4,5,6,4,5,6,7,
    5,6,7,8,3,4,5,6,4,5,6,7,5,6,7,8,6,7,8,9,1,2,3,4,2,3,4,5,3,4,5,6,4,5,6,7,2,3,4,5,3,4,5,6,
    4,5,6,7,5,6,7,8,3,4,5,6,4,5,6,7,5,6,7,8,6,7,8,9,4,5,6,7,5,6,7,8,6,7,8,9,7,8,9,10
};
const uint8_t digsum_of_n_base5[kIntSeqLen] = {
    0,1,2,3,4,1,2,3,4,5,2,3,4,5,6,3,4,5,6,7,4,5,6,7,8,1,2,3,4,5,2,3,4,5,6,3,4,5,6,7,4,5,6,7,8,5,6,
    7,8,9,2,3,4,5,6,3,4,5,6,7,4,5,6,7,8,5,6,7,8,9,6,7,8,9,10,3,4,5,6,7,4,5,6,7,8,5,6,7,8,9,6,7,8,9,
    10,7,8,9,10,11,4,5,6,7,8,5,6,7,8,9,6,7,8,9,10,7,8,9,10,11,8,9,10,11,12,1,2,3
};
const uint8_t count_down_by_2[kIntSeqLen] = {
    1,2,3,1,4,2,5,3,1,6,4,2,7,5,3,1,8,6,4,2,9,7,5,3,1,10,8,6,4,2,11,9,7,5,3,1,12,10,8,6,4,2,13,11,9,
    7,5,3,1,14,12,10,8,6,4,2,15,13,11,9,7,5,3,1,16,14,12,10,8,6,4,2,17,15,13,11,9,7,5,3,1,18,16,14,12,
    10,8,6,4,2,19,17,15,13,11,9,7,5,3,1,20,18,16,14,12,10,8,6,4,2,21,19,17,15,13,11,9,7,5,3,1,22,20,18,16,14,12,10
};
const uint8_t interspersion_of_A163253[kIntSeqLen] = {
    1,2,3,1,2,4,3,5,1,2,4,6,3,5,7,1,2,4,6,8,3,5,7,9,1,2,4,6,8,10,3,5,7,9,11,1,2,4,6,8,10,12,3,5,7,
    9,11,13,1,2,4,6,8,10,12,14,3,5,7,9,11,13,15,1,2,4,6,8,10,12,14,16,3,5,7,9,11,13,15,17,1,2,4,6,
    8,10,12,14,16,18,3,5,7,9,11,13,15,17,19,1,2,4,6,8,10,12,14,16,18,20,3,5,7,9,11,13,15,17,19,21,1,2,4,6,8,10,12,14
};
}
// Trigger-delay tick counts. Vendor OC_strings.cpp:341 (namespace OC, not
// OC::Strings). Harrington 1200's TriggerDelays::Process indexes this by the
// selected delay setting.
const uint8_t trigger_delay_ticks[kNumDelayTimes] = {
    0, 2, 4, 6, 8, 16, 33, 66
};
}

HSClockManager clock_m;

// Time-injection override-global. Consumed-and-cleared inside
// hemispheres_shim::step(); set by harness helper
// hem_test::step_n_inner_ticks. Zero means "use default numFrames/3".
namespace hem_shim { int inner_ticks_override = 0; }

uint32_t hem_rng_state = 0x12345678u;

#include "HSIOFrame.h"
HS::IOFrame HS::frame;

void HS::IOFrame::ClockOut(DAC_CHANNEL ch, int pulselength) {
    if (pulselength <= 0) pulselength = HEMISPHERE_CLOCK_TICKS;
    outputs[ch].set(PULSE_VOLTAGE * ONE_OCTAVE);
    clock_countdown[ch] = pulselength;
}

#include "CVInputMap.h"
CVInputMap cvmap[4] = {CVInputMap(0), CVInputMap(1), CVInputMap(2), CVInputMap(3)};
DigitalInputMap trigmap[4] = {DigitalInputMap(0), DigitalInputMap(1), DigitalInputMap(2), DigitalInputMap(3)};

// Vendor SegmentDisplay::digit is declared `static constexpr uint8_t digit[10]`
// inside the class body but never defined out-of-class. Under C++11/14 (our
// arm build is -std=c++11) the array is odr-used by SegmentDisplay::Print()
// at SegmentDisplay.h:130 and requires a definition. NT firmware reports the
// missing symbol (_ZN14SegmentDisplay5digitE) at on-device link time even
// though `make arm` succeeds at .o build time. Provide the definition here.
#include "hem_graphics.h"
#include "../../vendor/O_C-Phazerville/software/src/SegmentDisplay.h"
constexpr uint8_t SegmentDisplay::digit[10];
